_BASE_: "keypoint_rcnn_R_101_FPN_3x.yaml"
SOLVER:
  CHECKPOINT_PERIOD: 250
  IMS_PER_BATCH: 6
  MAX_ITER: 15000
  BASE_LR: 0.0025
DATASETS:
  TRAIN: ("keypoints_coco_gs_train",)
  TEST: ("keypoints_coco_gs_val",)
